name: build

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ started ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          # cache: gradle

      - name: set local.properties
        run: |
          echo debug_store_password="${{ secrets.RELEASE_STORE_PASSWORD }}" >> local.properties
          echo debug_key_alias="${{ secrets.RELEASE_KEY_ALIAS }}" >> local.properties
          echo debug_key_password="${{ secrets.RELEASE_KEY_PASSWORD }}" >> local.properties
          echo debug_store_file=~/release.jks >> local.properties

          echo release_store_password="${{ secrets.RELEASE_STORE_PASSWORD }}" >> local.properties
          echo release_key_alias="${{ secrets.RELEASE_KEY_ALIAS }}" >> local.properties
          echo release_key_password="${{ secrets.RELEASE_KEY_PASSWORD }}" >> local.properties
          echo release_store_file=~/debug.jks >> local.properties

      - name: generate key store
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_XML_ASC_BASE64 }}" |
          base64 --decode |
          gpg -d --passphrase "${{ secrets.GOOGLE_SERVICES_XML_ASC_BASE64_PASSPHRASE }}" --batch > app/src/main/res/values/google-services.xml

          echo "${{ secrets.RELEASE_JKS_ASC_BASE64 }}" | base64 --decode > ~/release.jks.asc
          gpg -d --passphrase "${{ secrets.RELEASE_JKS_ASC_PASSPHRASE }}" --batch ~/release.jks.asc > ~/release.jks

          echo "${{ secrets.RELEASE_JKS_ASC_BASE64 }}" | base64 --decode > ~/debug.jks.asc
          gpg -d --passphrase "${{ secrets.RELEASE_JKS_ASC_PASSPHRASE }}" --batch ~/debug.jks.asc > ~/debug.jks

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build

      - name: upload outputs
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: app/build/outputs

      - name: upload apk debug
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: upload apk release
        uses: actions/upload-artifact@v2
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk
